### ISSUE TITLE
Parser should reject any header with a count of zero objects

### ISSUE THREAD

**Issue by jadamcrain** [pesco/dnp3#10]
Although not explicitly disallowed by the specification, there is never a case where a header with an count of 0 objects is semantically meaningful. I have seen implementations choke on this sadly b/c they had a bad assumption in somewhere that it would always be at least one object.

Recommend explicitly rejecting "count" and "count and prefix" type headers with the count field set to zero.

I've add some test cases:

https://github.com/jadamcrain/dnp3/blob/master/test/unit/main.c#L133

**Comment by pesco** [comment]
4a31af9
