### ISSUE TITLE
4-byte integer overflow in start/stop qualifer

### ISSUE THREAD

**Issue by jadamcrain** [pesco/dnp3#9]
https://github.com/jadamcrain/dnp3/blob/master/test/unit/main.c#L756

Parser incorrectly interprets this as a valid ASDU, presumably b/c of a 32-bit integer overflow.

gtest output

```
GTest: run: /app/range/overflow
(MSG: Parse used 100107 bytes, wasted 6885 bytes. Inefficiency: 6.435061%)
(MSG: Check failed on line 85: (cres == result) ([0] RESPONSE {g30v2 qc=02 #0..4294967295} == PARAM_ERROR on [0] RESPONSE))
(MSG: Parse used 198811 bytes, wasted 6917 bytes. Inefficiency: 3.362206%)
GTest: result: FAIL
```

**Comment by pesco** [comment]
Damn! How did this get through. :) Those type conversions...

**Comment by jadamcrain** [comment]
https://github.com/jadamcrain/dnp3/blob/master/src/oblock.c#L77

Have to use uint64_t to represent "count of objects" when use 32-bit ranges. I have seen some implementations explicitly disallow stop == 0xFFFFFFFF just so that they could avoid having to do 64-bit math. That's an interesting solution to the problem, because that precondition ensures (stop - start +1) can't overflow.

**Comment by pesco** [comment]
Adam Crain notifications@github.com writes:

> https://github.com/jadamcrain/dnp3/blob/master/src/oblock.c#L77
> 
> Have to use uint64_t to represent "count of objects" when use 32-bit
> ranges.

Indeed. The tragedy is that I was explicitly thinking of this case with
the validation but still made the erroneous downcast! m)

Will touch all this tomorrow; I finished up Hammer's (out of) memory
handling today.

**Comment by jadamcrain** [comment]
BTW, I replied to your previous email from last week, but just got a notification that "delivery was delayed". Have you gotten any emails from me in last 2 days?

**Comment by pesco** [comment]
0067701
